// flow-typed signature: c1746f7bbb3cd288ec2c15355f99a027
// flow-typed version: <<STUB>>/eslint-plugin-styled-components-config_v^0.0.2/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-styled-components-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-styled-components-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-styled-components-config/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-styled-components-config/lib/rules/display-name-required' {
  declare module.exports: any;
}

declare module 'eslint-plugin-styled-components-config/tests/lib/rules/display-name-required' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-styled-components-config/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-styled-components-config/lib/index'>;
}
declare module 'eslint-plugin-styled-components-config/lib/rules/display-name-required.js' {
  declare module.exports: $Exports<'eslint-plugin-styled-components-config/lib/rules/display-name-required'>;
}
declare module 'eslint-plugin-styled-components-config/tests/lib/rules/display-name-required.js' {
  declare module.exports: $Exports<'eslint-plugin-styled-components-config/tests/lib/rules/display-name-required'>;
}
